version: '3.7'

services:
    redis:
        image: "redis:alpine"
        ports:
        - "${REDIS_PORT}:6379"
    main:
        build: .
        volumes:
            - .:/usr/src/app
            - /main/node_modules
        ports:
            - ${PORT}:${PORT}
        command: npm start
        restart: on-failure
        read_only: true
        env_file:
            - .env